<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'http-client' => GuzzleHttp\Client::class,
    'user'  =>  [
        'autoPass'  =>  'autoGeneratedPassword_123aa123'
    ],
    'vk'    =>  [
        'appId' =>  '5884654',
        'apiSecret' =>  'JQH13ZiUg74j8HCTubGO',
        'callbackUrl'   =>  'http://micro-frontend'
    ]
];
